export const zh = {
  nav: {
    intelligence: "智能分析",
    overview: "概览",
    opportunities: "招标机会",
    aiAnalysis: "AI 分析",
    operations: "运营",
    sources: "数据源",
    crawlLogs: "抓取日志",
    savedSearches: "保存搜索",
    system: "系统",
    settings: "设置",
  },
  common: {
    loading: "加载中…",
    error: "出错了",
    tryAgain: "重试",
    refresh: "刷新",
    save: "保存",
    cancel: "取消",
    delete: "删除",
    apply: "应用",
    export: "导出",
    search: "搜索",
    all: "全部",
    active: "活跃",
    inactive: "未激活",
    enabled: "已启用",
    disabled: "已禁用",
    viewAll: "查看全部",
    open: "查看",
    prev: "上一页",
    next: "下一页",
    showing: "显示",
    of: "/",
    results: "条结果",
    page: "页",
    noData: "暂无数据",
    dismiss: "关闭",
    signOut: "退出登录",
    staySignedIn: "保持登录",
    sessionExpiring: "由于长时间未操作，您的会话即将过期。",
  },
  dashboard: {
    commandCenter: "指挥中心",
    totalLeads: "相关线索",
    highlyRelevant: "高关联",
    new24h: "新增 (24h)",
    closingSoon: "即将截止",
    topOpportunities: "热门机会",
    relevanceDistribution: "关联度分布",
    sourcePerformance: "数据源表现",
    aiIntelligence: "AI 分析",
    pipeline: "工作流",
    sourceHealth: "数据源健康",
    activeSources: "活跃源",
    crawls24h: "24h 抓取",
    analyzed: "已分析",
    avgScore: "平均分",
    pursue: "推进",
    review: "待审",
    skip: "跳过",
    viewReports: "查看所有报告 →",
    details: "详情",
    runCrawler: "运行抓取",
    crawlerDispatched: "抓取器已启动，请查看日志了解进度。",
    noOpportunities: "暂无招标机会，运行抓取器开始收集。",
    found: "发现",
    new: "新增",
    viewLogs: "查看日志",
    totalOpps: "总机会数",
    procurementIntelligence: "采购智能平台",
  },
  opportunities: {
    title: "招标机会",
    searchPlaceholder: "搜索百叶窗、窗帘、遮光帘、床品…",
    focusMode: "聚焦模式",
    score: "评分",
    bucket: "关联度",
    organization: "发标机构",
    closing: "截止日期",
    analysis: "分析",
    opportunity: "招标机会",
    noMatch: "没有匹配筛选条件的机会",
    adjustFilters: "请调整搜索或筛选条件",
  },
  detail: {
    backToOpportunities: "返回机会列表",
    notFound: "机会未找到",
    notFoundDesc: "该机会不存在或已被删除。",
    opportunityDetails: "机会详情",
    viewOriginal: "查看原文",
    description: "描述",
    descNotAvailable: "暂无描述 — 请查看原始招标文件。",
    contact: "联系方式",
    whyMatched: "匹配原因",
    businessFit: "业务匹配",
    industryTags: "行业标签",
    upgradeReanalyze: "升级 / 重新分析",
    upgradeDeep: "升级为深度分析",
    reanalyze: "重新分析 (消耗 AI 额度)",
    summary: "摘要",
    analysisTab: "分析",
    documents: "文件",
    evidence: "证据",
    notes: "备注",
    noNotes: "暂无备注。",
    addNote: "添加备注",
    addNotePlaceholder: "添加备注…",
  },
  filters: {
    relevantOnly: "仅相关",
    highlyRelevant: "高关联",
    moderate: "中关联",
    lowRelevance: "低关联",
    irrelevant: "无关联",
    allBuckets: "全部分类",
    highestRelevance: "最高关联度",
    newest: "最新",
    closingSoon: "即将截止",
    allStatuses: "全部状态",
    open: "开放",
    closed: "已关闭",
    awarded: "已授标",
    cancelled: "已取消",
    allCountries: "全部国家",
    canada: "加拿大",
    unitedStates: "美国",
    allStages: "全部阶段",
    more: "更多",
    clear: "清除",
    minScore: "最低评分",
    after: "之后",
    before: "之前",
  },
  workflow: {
    new: "新建",
    hot: "紧急",
    review: "待审",
    shortlisted: "候选",
    pursuing: "跟进中",
    bid_submitted: "已投标",
    won: "已中标",
    lost: "未中标",
    passed: "已跳过",
    not_relevant: "不相关",
    monitor: "监控",
    rfq_sent: "已发询价",
    bid_drafted: "标书草拟",
  },
  bucket: {
    highly_relevant: "高关联",
    moderately_relevant: "中关联",
    low_relevance: "低关联",
    irrelevant: "无关联",
  },
  sources: {
    title: "数据源",
    registered: "已注册源",
    critical: "关键",
    high: "高",
    medium: "中",
    low: "低",
    experimental: "实验",
    recalculate: "重新计算",
    activeSources: "活跃源",
    totalOpps: "总机会数",
    relevantCollected: "相关收集",
    avgFitScore: "平均匹配分",
    searchSources: "搜索数据源…",
    allPriorities: "全部优先级",
    allHealth: "全部健康状态",
    source: "数据源",
    priority: "优先级",
    type: "类型",
    access: "接入方式",
    region: "地区",
    fit: "匹配度",
    opps: "机会",
    relevant: "相关",
    yieldPct: "转化率",
    runs: "运行",
    health: "健康度",
    lastCrawled: "上次抓取",
    noSources: "尚未配置数据源。",
    noMatch: "没有匹配的数据源。",
    healthy: "健康",
    degraded: "降级",
    failing: "故障",
    unsupported: "不支持",
    untested: "未测试",
  },
  logs: {
    title: "抓取日志",
    subtitle: "数据源抓取执行历史",
    totalRuns: "总运行",
    runsOnPage: "本页运行",
    completed: "已完成",
    failed: "失败",
    runningPending: "运行中 / 等待",
    oppsFoundInserted: "发现 / 新增",
    crawlRunHistory: "抓取运行历史",
    noCrawlRuns: "暂无抓取记录",
    clickToStart: "点击「运行抓取」开始首次抓取。",
    status: "状态",
    source: "数据源",
    trigger: "触发方式",
    started: "开始时间",
    duration: "耗时",
    pages: "页数",
    found: "发现",
    newCol: "新增",
    updated: "更新",
    error: "错误",
    localAgent: "本地代理",
  },
  intelligence: {
    title: "AI 智能分析报告",
    subtitle: "AI 驱动的招标分析，含可行性评分、范围提取和业务建议。",
    reports: "份报告",
    allReports: "全部报告",
    pursue: "推进",
    review: "待审",
    skip: "跳过",
    noReports: "暂无分析报告",
    noReportsDesc: "对招标机会运行 AI 分析管线以生成详细的招标情报报告。",
    feasibility: "可行性",
    viewReport: "查看报告",
    cnSourcingViable: "中国采购可行",
    cnSourcingLimited: "中国采购受限",
  },
  settings: {
    title: "设置",
    subtitle: "平台配置、管理操作和情报参考",
    general: "通用",
    crawling: "抓取",
    keywords: "关键词",
    systemTab: "系统",
    businessFocusMode: "业务聚焦模式",
    businessFocusDesc: "启用后，仪表盘将抑制低关联度噪音，突出显示与窗帘、纺织品和室内装饰相关的机会。此偏好保存在浏览器中。",
    adminActions: "管理操作",
    runCrawlers: "运行抓取器",
    runCrawlersDesc: "对所有活跃数据源启动抓取。机会将根据当前关键词模型自动评分。",
    runAllCrawlers: "运行全部抓取",
    recalcSourceAnalytics: "重新计算数据源分析",
    recalcDesc: "更新所有数据源的转化率分析、健康状态和机会计数。",
    recalculate: "重新计算",
    sourceStatus: "数据源状态",
    crawlSchedule: "抓取调度参考",
    keywordDictionary: "行业关键词字典",
    keywordDictDesc: "这些关键词在抓取器评分引擎中配置。如需修改请联系管理员。",
    primaryKeywords: "主要关键词",
    secondaryKeywords: "次要关键词",
    contextTerms: "上下文术语",
    negativeFilters: "负面关键词过滤",
    negativeDesc: "包含这些术语的机会将受到严重扣分。",
    scoringModel: "关联度评分模型",
    scoringDesc: "每个机会按 0–100 评分，使用关键词匹配、语义模式、数据源匹配奖励、标题加成和负面惩罚。",
    systemInfo: "系统信息",
    safetyRules: "安全规则",
    platformStack: "技术栈",
  },
  savedSearches: {
    title: "保存搜索",
    subtitle: "保存筛选组合以便快速访问",
    newSearch: "新建搜索",
    name: "名称",
    keyword: "关键词",
    relevance: "关联度",
    country: "国家",
    any: "任意",
    saveSearch: "保存搜索",
    noSearches: "暂无保存搜索。",
    noSearchesDesc: "在上方创建常用筛选组合的搜索。",
    filters: "筛选条件",
    created: "创建时间",
    actions: "操作",
    allOpportunities: "全部机会",
  },
  login: {
    title: "BidToGo",
    subtitle: "采购情报平台",
    welcome: "欢迎回来",
    signInDesc: "登录您的情报仪表盘",
    email: "邮箱地址",
    password: "密码",
    signIn: "登录",
    signingIn: "登录中...",
    invalidCredentials: "邮箱或密码错误",
    sessionExpired: "会话因长时间未操作已过期",
    aiPowered: "AI 驱动",
    realTimeData: "实时数据",
    enterprise: "企业级",
    copyright: "BidToGo · 北美采购情报",
  },
} as const;
